In this python notebook, I have applyied TF-IDF system recommendation. I have used two parameters,individually. In my first case, I used genred column to analyse how system recommendation works. Secondly, I use overview column for the same analysis. Eventually, with the data showed. I realized that using overview column is more precise than genres columns and it may be because of the fact that TF-IDF matrix is bigger as we can see in the script. Evidently, The validity of these results needs to be established using Cross-Validation or another metric. However, in order to the lack of time and to avoid making the file heavier. I just showed the results I got.

In [12]:
#Importing libraries.
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [13]:
# loading data.
df = pd.read_csv('datasets/new_movies_dataset.csv',
                           usecols=['title','overview','genres'])
df.head()

title  \
0                    toy story   
1                      jumanji   
2             grumpier old men   
3            waiting to exhale   
4  father of the bride part ii   

                                            overview  \
0  led by woody, andy's toys live happily in his ...   
1  when siblings judy and peter discover an encha...   
2  a family wedding reignites the ancient feud be...   
3  cheated on, mistreated and stepped on, the wom...   
4  just when george banks has recovered from his ...   

                       genres  
0   animation, comedy, family  
1  adventure, fantasy, family  
2             romance, comedy  
3      comedy, drama, romance  
4                      comedy

In [14]:
df.genres.isnull().sum()

0

In [15]:
# Getting the description of the movie title given.
movie_title = 'toy story'
desc = df[(df['title'] == movie_title)]['genres'].str.strip()[0]
desc

'animation, comedy, family'

In [16]:
# Computing all the TF-IDF features for all the genres.
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(df['genres'])
tfidf_matrix

<45363x24 sparse matrix of type '<class 'numpy.float64'>'
	with 99577 stored elements in Compressed Sparse Row format>

In [17]:
# Computing cosine similarities between movie title genre and the others genres.
tfidf_similarities = cosine_similarity(tfidf_matrix, tfidf.transform([desc]))
tfidf_similarities

array([[1.        ],
       [0.36314828],
       [0.22503408],
       ...,
       [0.        ],
       [0.        ],
       [0.        ]])

In [18]:
# Getting top 10 index from films which have the best match according to TF-IDF.
tfidf_similar_movie_indices = tfidf_similarities.argsort(axis=0)[-10:][::-1].flatten()
tfidf_similar_movie_indices

array([    0, 31209,  7432,  7723, 33194,  8201,  8241, 32442, 31881,
        9200], dtype=int64)

In [19]:
# Turn indexes into titles showing  off top 5 .
tfidf_similar_movie_titles = df.loc[tfidf_similar_movie_indices, 'title'].tolist()
tfidf_similar_movie_titles[1:6]

['tom and jerry spy quest',
 "bon voyage, charlie brown (and don't come back!)",
 'garfield',
 'hotel transylvania 2',
 "bébé's kids"]

**Now, I'll use overview column**

In [20]:
# Getting the description of the movie title given.
movie_title = 'toy story'
desc = df[(df['title'] == movie_title)]['overview'].str.strip()[0]
desc

"led by woody, andy's toys live happily in his room until andy's birthday brings buzz lightyear onto the scene. afraid of losing his place in andy's heart, woody plots against buzz. but when circumstances separate buzz and woody from their owner, the duo eventually learns to put aside their differences."

In [21]:
# Computing all the TF-IDF features for all the overviews.
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(df['overview'])
tfidf_matrix

<45363x76070 sparse matrix of type '<class 'numpy.float64'>'
	with 1883741 stored elements in Compressed Sparse Row format>

In [22]:
# Computing cosine similarities between movie title overview  and the others overviews.
tfidf_similarities = cosine_similarity(tfidf_matrix, tfidf.transform([desc]))
tfidf_similarities

array([[1.        ],
       [0.03099428],
       [0.01312044],
       ...,
       [0.00957572],
       [0.03557541],
       [0.01782177]])

In [23]:
# Getting top 10 index from films which have the best match according to TF-IDF.
tfidf_similar_movie_indices = tfidf_similarities.argsort(axis=0)[-10:][::-1].flatten()
tfidf_similar_movie_indices

array([    0, 15337,  2994, 10293, 24485, 23807, 29160, 43338, 38407,
        8321], dtype=int64)

In [24]:
# Turn indexes into titles showing off top 5 .
tfidf_similar_movie_titles = df.loc[tfidf_similar_movie_indices, 'title'].tolist()
tfidf_similar_movie_titles[1:6]

['toy story 3',
 'toy story 2',
 'the 40 year old virgin',
 'small fry',
 "andy hardy's blonde trouble"]